[package]
name = "electrum"
version = "0.1.0"
authors = ["jyoti swarup <jyoti.swarup@outlook.com>"]
edition = "2018"

[[bin]] 
name="electrum"
path = "src/electrum.rs"

[dependencies]
rand = "0.3.14"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
